import { NextRequest } from "next/server";
import { getCurrentEmployee } from "@/lib/dal";
import { getEntityContext } from "@/lib/entity";
import { buildWorkbook, excelResponseHeaders, type SheetColumn } from "@/lib/excel";
import { getReportDefinition } from "@/lib/reports/definitions";
import { runReport, ReportPermissionError } from "@/lib/reports/run";
import type { ReportFilters, ReportFilterKey } from "@/lib/reports/types";

const FILTER_KEYS: ReportFilterKey[] = [
  "entity",
  "dateFrom",
  "dateTo",
  "product",
  "supplier",
  "employee",
  "transactionType",
  "status",
];

/**
 * Exports any report to .xlsx using exactly the filters supplied in the query
 * string, so the file always matches what the user sees on screen.
 */
export async function GET(request: NextRequest) {
  const employee = await getCurrentEmployee();
  if (!employee) {
    return new Response("Not signed in.", { status: 401 });
  }
  if (!employee.permissions.includes("generate_exports")) {
    return new Response("You do not have permission to generate exports.", { status: 403 });
  }

  const params = request.nextUrl.searchParams;
  const reportId = params.get("report") ?? "";
  const definition = getReportDefinition(reportId);
  if (!definition) {
    return new Response("Unknown report.", { status: 404 });
  }

  const filters: ReportFilters = {};
  for (const key of FILTER_KEYS) {
    const value = params.get(key);
    if (value) filters[key] = value;
  }

  try {
    const result = await runReport(reportId, filters);
    const entityContext = await getEntityContext();

    const columns: SheetColumn[] = result.columns.map((column) => ({
      header: column.header,
      key: column.key,
      width: column.width,
    }));

    const meta: Array<[string, string]> = [
      ["Entity", filters.entity ? entityContext.entities.find((e) => e.id === filters.entity)?.name ?? "—" : entityContext.activeEntity?.name ?? "All entities"],
      ["Date range", `${filters.dateFrom || "Beginning"} to ${filters.dateTo || "Today"}`],
      ["Generated by", employee.full_name],
      ["Generated at", new Date().toISOString().replace("T", " ").slice(0, 19)],
      ["Rows", String(result.rows.length)],
    ];
    if (result.truncatedAt) {
      meta.push(["Note", `Truncated to the first ${result.truncatedAt} rows.`]);
    }

    const buffer = await buildWorkbook(definition.title, columns, result.rows, {
      title: definition.title,
      meta,
    });

    const filename = `${definition.id}-${new Date().toISOString().slice(0, 10)}.xlsx`;
    return new Response(new Uint8Array(buffer), { headers: excelResponseHeaders(filename) });
  } catch (error) {
    if (error instanceof ReportPermissionError) {
      return new Response(error.message, { status: 403 });
    }
    console.error("[reports] export failed", error);
    return new Response("Could not generate the export.", { status: 500 });
  }
}
