import type { ReportDefinition } from "./types";

/**
 * The complete Phase 1 report catalogue. The same definitions drive the report
 * picker, the filter bar, permission gating and the Excel export route, so a
 * report can never appear on screen without its query and permission.
 */
export const REPORT_DEFINITIONS: ReportDefinition[] = [
  {
    id: "current-stock",
    title: "Current Stock",
    description: "Live quantity and value on hand by product and batch.",
    group: "Stock",
    permission: "view_inventory",
    filters: ["entity", "product", "supplier"],
  },
  {
    id: "opening-stock",
    title: "Opening Stock",
    description: "Confirmed opening-stock entries with batch and cost detail.",
    group: "Stock",
    permission: "view_inventory",
    filters: ["entity", "dateFrom", "dateTo", "product", "status"],
  },
  {
    id: "stock-inward",
    title: "Stock Inward",
    description: "Purchases, free goods and replacements received into stock.",
    group: "Stock",
    permission: "view_inventory",
    filters: ["entity", "dateFrom", "dateTo", "product", "supplier", "transactionType", "status"],
  },
  {
    id: "stock-outward",
    title: "Stock Outward",
    description: "Sales, consumption, write-offs and supplier returns.",
    group: "Stock",
    permission: "view_inventory",
    filters: ["entity", "dateFrom", "dateTo", "product", "transactionType"],
  },
  {
    id: "stock-ledger",
    title: "Stock Ledger",
    description: "Every stock movement with running balance after each entry.",
    group: "Stock",
    permission: "view_inventory",
    filters: ["entity", "dateFrom", "dateTo", "product", "transactionType"],
  },
  {
    id: "low-stock",
    title: "Low Stock",
    description: "Products at or below their minimum stock quantity.",
    group: "Stock",
    permission: "view_inventory",
    filters: ["entity", "product", "supplier"],
  },
  {
    id: "out-of-stock",
    title: "Out of Stock",
    description: "Products with no sellable quantity remaining.",
    group: "Stock",
    permission: "view_inventory",
    filters: ["entity", "product", "supplier"],
  },
  {
    id: "stock-requirement",
    title: "Stock Requirement / Reorder",
    description: "Reorder quantities to reach each product's restock target, grouped by supplier.",
    group: "Stock",
    permission: "view_inventory",
    filters: ["entity", "supplier"],
  },
  {
    id: "supplier-purchases",
    title: "Supplier Purchases",
    description: "Confirmed purchase value by supplier and invoice.",
    group: "Purchasing",
    permission: "view_purchase_cost",
    sensitive: "cost",
    filters: ["entity", "dateFrom", "dateTo", "supplier"],
  },
  {
    id: "supplier-returns",
    title: "Supplier Returns",
    description: "Stock returned to suppliers with resolution and status.",
    group: "Purchasing",
    permission: "view_inventory",
    filters: ["entity", "dateFrom", "dateTo", "supplier", "status"],
  },
  {
    id: "free-goods",
    title: "Free Goods / FOC",
    description: "Free-of-charge and sample stock received.",
    group: "Purchasing",
    permission: "view_inventory",
    filters: ["entity", "dateFrom", "dateTo", "product", "supplier"],
  },
  {
    id: "replacement-goods",
    title: "Replacement Goods",
    description: "Replacement stock received, linked to the originating return.",
    group: "Purchasing",
    permission: "view_inventory",
    filters: ["entity", "dateFrom", "dateTo", "supplier"],
  },
  {
    id: "daily-sales",
    title: "Daily Sales",
    description: "Sales count, discount and revenue per day.",
    group: "Sales",
    permission: "create_sales",
    filters: ["entity", "dateFrom", "dateTo"],
  },
  {
    id: "product-sales",
    title: "Product-wise Sales",
    description: "Quantity and revenue sold per product.",
    group: "Sales",
    permission: "create_sales",
    filters: ["entity", "dateFrom", "dateTo", "product"],
  },
  {
    id: "employee-sales",
    title: "Employee-wise Sales",
    description: "Transactions, revenue and discount given per employee.",
    group: "Sales",
    permission: "view_management_reports",
    filters: ["entity", "dateFrom", "dateTo", "employee"],
  },
  {
    id: "entity-sales",
    title: "Entity-wise Sales",
    description: "Sales and revenue compared across entities.",
    group: "Management",
    permission: "view_management_reports",
    filters: ["dateFrom", "dateTo"],
  },
  {
    id: "daily-revenue",
    title: "Daily Revenue",
    description: "Revenue by day and payment method.",
    group: "Sales",
    permission: "view_management_reports",
    filters: ["entity", "dateFrom", "dateTo"],
  },
  {
    id: "gross-profit",
    title: "Gross Profit",
    description: "Revenue against cost of goods sold, per product.",
    group: "Management",
    permission: "view_profit",
    sensitive: "profit",
    filters: ["entity", "dateFrom", "dateTo", "product"],
  },
  {
    id: "discount-report",
    title: "Discount Report",
    description: "Discounts given by employee and invoice.",
    group: "Management",
    permission: "view_management_reports",
    filters: ["entity", "dateFrom", "dateTo", "employee"],
  },
  {
    id: "cost-vs-price",
    title: "Purchase Cost vs Selling Price",
    description: "Configured cost, selling price and margin per product.",
    group: "Management",
    permission: "view_purchase_cost",
    sensitive: "cost",
    filters: ["entity", "product", "supplier"],
  },
  {
    id: "consolidated",
    title: "Consolidated Multi-Entity Report",
    description: "Sales, profit, stock value and low-stock counts for every entity.",
    group: "Management",
    permission: "view_management_reports",
    sensitive: "profit",
    filters: ["dateFrom", "dateTo"],
  },
];

export function getReportDefinition(id: string): ReportDefinition | undefined {
  return REPORT_DEFINITIONS.find((report) => report.id === id);
}
